### ISSUE TITLE
Plot title is out of display.

### ISSUE THREAD

**Issue by bicycle1885** [JuliaPlots/StatPlots.jl#14]
Hi, thank you for making such a brilliant package in Julia.

I encountered a problem in which I cannot see a plot title because it seems to be out of window. Here is an example:
<img width="878" alt="screen shot 2016-09-30 at 9 35 12" src="https://cloud.githubusercontent.com/assets/905683/18977689/6ddf6dc0-86f7-11e6-9d76-3a6f899ec637.png">

I made this plot with `corrplot(θ[:,1001:2000]', title="NUTS", markersize=1)` using the GR backend but the title ("NUTS") is not displayed and small fraction of the plot is also out of display.

This is a complete reproducing script: https://gist.github.com/bicycle1885/77d7ad79fbd3fa195ff432be167812d6

**Comment by tbreloff** [comment]
Thanks for the report and the complement. That plot looks cool. :)  You can
always play with top_margin to hack it.

**Comment by bicycle1885** [comment]
Thanks. I've tried `top_margin` but now it looks like this:
<img width="878" alt="screen shot 2016-09-30 at 11 17 03" src="https://cloud.githubusercontent.com/assets/905683/18978625/8ea51ebc-86ff-11e6-9bc7-e46276779a4a.png">

Here is the command: `julia> corrplot(θ[:,1001:2000]', title="NUTS", markersize=1, top_margin=15mm)`. The `top_margin` seems to insert a margin for each subplot and doesn't allocate enough space as a whole, though I may misunderstand something trivial.

**Comment by tbreloff** [comment]
Sorry I'm looking at this again and I read it too quickly before.  The attribute `title` is a subplot attribute, so this is trying to add title "NUTS" to **every** subplot.  However, the corrplot recipe is tricky in that it explicitly sets the titles for only the top row, and it uses whatever you set for `labels`.  So to be tricky you'd need to do something like:

```julia
julia> using StatPlots; gr()
Plots.GRBackend()

julia> n = 5
5

julia> labs = fill("",1,n); labs[div(n,2)+1] = "NUTS"; labs
1×5 Array{String,2}:
 ""  ""  "NUTS"  ""  ""

julia> corrplot(rand(1000,n), labels=labs)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/19200327/71e9892e-8c96-11e6-8cbb-6ba01615d1ae.png)


and since I've written this out and it's sooooo hacky and bad, I'll fix it inside corrplot...

**Comment by tbreloff** [comment]
```julia
using StatPlots; pyplot()
corrplot(randn(100,5), title="NUTS", ms=1, labels = map(i->"lab$i",1:5))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/19200709/70d76d88-8c98-11e6-8059-e4cda0badcff.png)

**Comment by bicycle1885** [comment]
Thank you!
