### ISSUE TITLE
Density: Can't set path color

### ISSUE THREAD

**Issue by sebastianpech** [JuliaPlots/StatPlots.jl#48]
```
using Plots
using StatPlots

density(randn(200),color=:red)
cdensity!(randn(200),color=:red)
```

The path for `density` is black, the path for `cdensity` is red. I'm having everything on master. Tested with:

- pyplot
- plotlyjs
- gr

I looked into the recipe code but I can't see any difference between `density` and `cdensity` that could cause this behavior. Setting the `linestyle` works.

**Comment by mkborregaard** [comment]
This appears to be some kind of namespace clash. Swapping the names of `cdensity` and `density` series recipes, the recipe now named `density` stops working. Simply renaming the `density` recipe to `densit` also restores function.

**Comment by mkborregaard** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/727
The issue was that density (but not cdensity) was registered as like_histogram, a group whose only purpose was to make `linecolor` default to black, rather than to `color` (so `linecolor = :red` worked all along). This is unintuitive behaviour, so I removed density from like_histogram.

**Comment by sebastianpech** [comment]
I see, thanks for fixing it that quickly.
